---
trigger: none


variables:
  - group: VCPI-GitHub
  - name: tokengithub
    value: https://silvio:$(GITHUB_TOKEN_ALL_REPOSITORIES)@github.com

parameters:
  - name: maintainerversion
    displayName: What is the new Major.Minor Version?
    type: string
  - name: patchlevelversion
    displayName: What is the patchlevel?
    type: string
    default: 0

jobs:
  - job: resetnumber
    displayName: Reseting Maintainer Number to ${{parameters.maintainerversion}}.${{parameters.patchlevelversion}}

    pool:
      name: FirmwareTestpool

    steps:
      - checkout: self
        enabled: true
        persistCredentials: true

      - bash: |
          cat <<-EOM > version.maintainer.env
          VERSION_ENV="${{parameters.maintainerversion}}"
          EOM

          cat <<-EOM > version.patchlevel.env
          # This file contains the versionnumber of the last build or was newly generated.
          VERSION_PATCHLEVEL_FILE_CHANGED="$(date --iso-8601=s)"
          VERSION_PATCHLEVEL_NUMBER="${{parameters.patchlevelversion}}"
          EOM

          SOURCEBRANCH="${BUILD_SOURCEBRANCH#refs/heads/}"

          echo ":: commit to ${SOURCEBRANCH}"
          git add version.maintainer.env version.patchlevel.env
          git \
            -c user.name="${BUILD_REQUESTEDFOR}" \
            -c user.email="${BUILD_REQUESTEDFOREMAIL}" \
            commit \
              -m "version: Update to ${{parameters.maintainerversion}}.${{parameters.patchlevelversion}}"

          echo ":: push to ${SOURCEBRANCH}"
          git push origin HEAD:"${SOURCEBRANCH}"
